copy-tag,image-metadata добавил шаблонизацию в параметр repo-name

diff --git a/.github/workflows/build-generate-tag.yaml b/.github/workflows/build-generate-tag.yaml
--- a/.github/workflows/build-generate-tag.yaml
+++ b/.github/workflows/build-generate-tag.yaml
@@ -43,5 +43,14 @@ jobs:
             git config --global user.name "${AUTHOR_NAME}"
             git add ./generate-tag/dist
             git commit -m "build generate-tag action"
-            git push origin ${{ github.ref }}:${{ github.ref }}   
+            while true; do
+              if ! git push origin ${{ github.ref }}:${{ github.ref }}; then
+                echo "Push failed, sleep 10 seconds and retrying..."
+                git pull --rebase
+                sleep 10
+                continue
+              else
+                break
+              fi
+            done
           fi
diff --git a/.github/workflows/build-main-action.yaml b/.github/workflows/build-main-action.yaml
--- a/.github/workflows/build-main-action.yaml
+++ b/.github/workflows/build-main-action.yaml
@@ -42,5 +42,14 @@ jobs:
             git config --global user.name "${AUTHOR_NAME}"
             git add ./js-action/dist
             git commit -m "builded action"
-            git push origin ${{ github.ref }}:${{ github.ref }}   
+            while true; do
+              if ! git push origin ${{ github.ref }}:${{ github.ref }}; then
+                echo "Push failed, sleep 10 seconds and retrying..."
+                git pull --rebase
+                sleep 10
+                continue
+              else
+                break
+              fi
+            done
           fi
